---
# Create an instance and refer existing default or none default VPC. Since referencing a subnetId will automatically place the instance within the correct VPC we don't need to reference VPC here.
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-1a
      ImageId: ami-0bdb828fd58c52235
      InstanceType: t2.micro
      # Add the SG ID to reference instance which SG to pick.
      SecurityGroupIds:
        - sg-xxxxxxxxxx
      # Add the SubnetId to reference the existing subnet.
      SubnetIds:
        - subnet-xxxxxxxxx